version: '3.7'
services:
    whoami:
        image: containous/whoami
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.whoami.rule=Host(`example.com`)"
            - "traefik.http.routers.whoami.tls.certresolver=do"
        networks:
            - web            
networks:
    web:
        external: true